name: Terraform pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  run-terraform:
    name: "Run terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup terraform
        uses: "hashicorp/setup-terraform@v3"
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve
